name: kargo_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter    


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  persistent_bottom_nav_bar: ^5.0.1

  flutter_svg: ^1.1.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.2
  badges: ^3.1.1
  dotted_line: ^3.2.2 
  flutter_dash: ^1.0.0
  flutter_native_splash: ^2.2.17
  flutter_launcher_icons: "^0.13.1"
  zoom_widget: ^2.0.1
  dio: ^5.3.1
  
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^15.1.0+1
  photo_view: ^0.14.0
  editable: ^2.0.0
  get: ^4.6.6
  flutter_phone_direct_caller: ^2.1.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/languages/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin_Condensed-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: ALSHauss
      fonts:
        - asset: assets/fonts/ALSHauss.ttf


